title: Xuehang Wen's Homepage
page-top-title: Xuehang Wen
top-section-bg-text: Art and Design
home-subtitle:  Xuehang Wen&ensp;|&ensp;温雪航
copyright-text: '&copy; Xuehang Wen 2023-2026. All Rights Reserved.'
baseURL: "https://susan-18.github.io/xuehangwen.github.io/"
